services:
  - type: web
    name: flexit-backend
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: bash -c "flask db upgrade && gunicorn backend.wsgi:app"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flexit-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: JWT_SECRET_KEY
        generateValue: true

      - key: QR_SECRET
        generateValue: true

      - key: FLASK_ENV
        value: production

      - key: ALLOWED_ORIGINS
        value: https://flex-it-six.vercel.app

databases:
  - name: flexit-db
    databaseName: flexitdb
    user: flexitdb_user